### ISSUE TITLE
Tutorials todo list

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#153]
Wishlist / todo list for tutorials: 

* [x] deflation
* [x] MATLAB 1: When a user has an application only implemented in MATLAB:  `compute_Mder()` is available in MATLAB. Show how a user can still use our library (although not very efficiently).
* [ ] ~MATLAB 2:~ When an SPMF is available in MATLAB. (Preferably with an `DerSPMF` precomputation as a last improvement) 
* [ ] ~Paradiso:~ Show how to use a different linear solver (requires Intel MKL .. :( ) 
* [x] python: an application implemented in python (?) 
* [ ] ~bifurcation~: showing to generate bifurcation diagram for a simple problem (e.g. like the figure in dde-biftool  http://ddebiftool.sourceforge.net/demos/neuron/html/demo1_stst.html#8 )
* [ ] ~DifferentialEquations.jl:~ An example where the discretization stems from julias framework for differential equations
* [x] An example generated by gmsh, e.g.  based on https://gitlab.onelab.info/doc/models/tree/master/NonLinearEVP
* [ ] ~An example illustrating projected solve~ 
* [x] An example with application from fluid mechanics (udpup)
* [x] A preconditioner GMRES 
* [x] Parallellization tutorial: e.g. a parallell computation call to contour_beyn
* [x] Fortran: Showing how to solve problems defined with external code (fortran)

**Comment by jarlebring** [comment]
Added more items after some discussions with @upadpup.

**Comment by jarlebring** [comment]
Added a fortran tutorial: https://nep-pack.github.io/NonlinearEigenproblems.jl/tutorial_fortran1/
