### ISSUE TITLE
Checklist for migration of unit testing

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#31]
Functionality which needs unit test (migrated from kth github # 28)

run-scripts which should be migrated:

- [x] `run_test_comp.jl`  @upadpup 
- [x] `run_test_eigenvector_extraction*.jl` @gmele 
- [x] `run_test_TIAR.jl` @gmele 
- [x] `run_test_scaling.jl`  @eliasj 
- [x] `run_test_sg.jl`   @eringh (?)
- [x] `run_test_jd_quad.jl` @eringh (?)
