### ISSUE TITLE
Checklist version 0.2.0

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#96]
From our meeting 2018-09-19: Update as you feel appropriate:

 + [x] Basic restart for nlar Parik  
 + [x] (documenation online + function doc, emil)
 + [ ] (avoid function points in waveguide, emil)
 + [x] gallery structure, emil
 + [x] Rewrite SPMF (type stable + efficiency) elias
    - [x] Type stable spmf + abstract type  
    - [x] Native higher order derivatives 
 + [ ] cork implementation max
 + [x] TIAR / IAR proper function comments gmele
 + [x] compute_y0-documentation gmele
 + [x] rfi, implicitdet, newtonqr proper function comments parik
 + [x] LinSolvers documentation elias
 + [x] extend projection matrices elias
 + [x] Improve compute_Mlincomb(PEP) gmele 

Planned release: Oct 2

**Comment by meleg** [comment]
Here comes a short illustration of the performances of new compute_Mlincomb for PEP.
This is the new function against the old function
```
  0.025811 seconds (129 allocations: 64.092 MiB, 9.59% gc time)
  1.704403 seconds (103 allocations: 880.690 MiB, 19.56% gc time)
Error=3.999509374488596e-13
```
For the instance described in the following script.
```
using NonlinearEigenproblems
using LinearAlgebra
using Random
using SparseArrays

n=100000;
Random.seed!(1) # reset the random seed
K=[1:n;2:n;1:n-1]; J=[1:n;1:n-1;2:n]; # sparsity pattern of tridiag matrix
A1=sparse(K, J, rand(Float32,3*n-2)); A2=sparse(K, J, rand(Float32,3*n-2)); A3=sparse(K, J, rand(Float32,3*n-2)); A4=sparse(K, J, rand(Float32,3*n-2))

AA = [A1,A2,A3,A4]; nep=PEP(AA)
n=size(nep,1);	k=50; V=rand(n,k);	λ=rand()*im+rand(); a=rand(k)

z1=compute_Mlincomb(nep,λ,copy(V),a)
@time z1=compute_Mlincomb(nep,λ,V,a)
# old way of compute_Mlincomb used for SPMF
import NonlinearEigenproblems.NEPCore.compute_Mlincomb_from_MM
z2=compute_Mlincomb_from_MM(nep,λ,V,a)
@time z2=compute_Mlincomb_from_MM(nep,λ,V,a)
println("Error=",norm(z1-z2))
```

**Comment by maxbennedich** [comment]
Quite an improvement!

**Comment by jarlebring** [comment]
I see some documentation commits/PRs. Some recommendations to make it look nice and consistent: 

* The first line in the function/type doc should have four spaces before the function. If you write ?XX you will see that it matters for the formating
* Remember to surround your code with ` ```julia-repl  CODE ``` ` in the example. You can see how it looks with ?XX . 
* For NEP-algorithms, in order avoid repetition, I suggest that we refer to `newton` for most of the arguments. Recommended "See [newton](@ref) for description of the other parameters.`
* Properties or descriptions in common for all/most NEP-methods  can be directly added to `newton`.

**Comment by jarlebring** [comment]
The files Manifest.toml and Project.toml have grown substantially the last couple of weeks. I think it is nice to keep the number of dependencies low. Before the release, I suggest we reduce the number of dependencies. At the next meeting we remind everyone how to install packages without adding them to the package ;-)

**Comment by meleg** [comment]
@upadpup, is the restart for `nlar` completed? Can we check it from the list?

**Comment by maxbennedich** [comment]
> The files Manifest.toml and Project.toml have grown substantially the last couple of weeks.

I think I'm responsible for most of that in conjunction with the benchmark updates. It would be great if we could separate out the dependencies only needed for testing/benchmarking. Not quite sure what's the best way to do that. There's actually support to have separate dependencies for testing in `Project.toml`, but as far as I can tell, it only works with the `Pkg.test()` command (by creating a new temporary environment). Having a separate repository is of course an option, but one I'm not so fond of.

**Comment by meleg** [comment]
I do not know how much I should expand the documentation of compute_y0 for iar_cheb (it is one of the checkpoints). When I wrote these function and I left the comments "TODO: write documentation" I referred to document the mathematical formulas in the manuscript, that is done right now. Do you think it is needed more comments or different explanations?

Moreover, should we use math formulas as comment in the code? Sometimes I do in my own projects but it looks not so nice when there are more users.  I did it also in iar_cheb for example. Should I take away all the formulas? Suggestions?

**Comment by jarlebring** [comment]
The reason it ended up on the checklist was because at moment it is nowhere written how to use `compute_y0`, not because there was a todo.

I propose: 

1. Add function documentation to `compute_y0' including formulas defining the quantities. See function documentation of ?newton for use of latex and https://nep-pack.github.io/NonlinearEigenproblems.jl/methods/

2. Expand the function documentation of iar_chebyshev, with a reference to compute_y0:  
```
[`iar_chebyev`](@ref)
```

While I'm still commenting in that area: Could you go through the function documenation of iar, tiar and iar_chebyshev, and 1) make them consistent with the other function documentations (no headlines), 2) Expand the function doc to include non-standard arguments.

**Comment by upadpup** [comment]
@jarlebring Should we make proper function comments for all helper functions, for example the eigenvalue sorting functions in nlar.jl?

**Comment by upadpup** [comment]
@meleg Yes, restarting is implemented and hence I have ticked it off now.

**Comment by upadpup** [comment]
Proper function comments for rfi, implicitdet and newtonqr are now available.

**Comment by jarlebring** [comment]
Great. A short comment on eigval sorter (and in particular what argument the function takes) would be nice, e.g., as a part of the function documentation of `nlar`. 

For everyone: We should remember to give credit to the author who invented the algorithm, not only cite summary paper. (Fixed some occurences in the prev commit.)

**Comment by eringh** [comment]
Restructuring of Gallery fixed in #123.

**Comment by jarlebring** [comment]
As agreed, cork and waveguide can wait until next release. The release 0.2.0 is now completed, assuming the  application to include it in the registry goes through directly.
